<a href="https://colab.research.google.com/github/Ricardoarteaga24/InteligenciaArtificial_8vo/blob/main/Array_Numpy___29_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**LIBRERIA NUMPY**

In [2]:
#importar libreria
import numpy as np

In [4]:
print(np.__version__)

1.26.4


In [5]:
#crea array
myArray = np.array([1,2,3,4,5])
print(myArray)

[1 2 3 4 5]


In [6]:
#verifica que tipo es
print(type(myArray))

<class 'numpy.ndarray'>


In [7]:
print(myArray.shape)

(5,)


In [9]:
#imprimir valores
print(myArray.shape)
print(myArray[2])
myArray[2] = 10
print(myArray)

(5,)
3
[ 1  2 10  4  5]


**Rango 2 **

In [10]:
myarray1 = np.array([[1,2,3],[4,5,6]])
print(myarray1)
print(myarray1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [11]:
myarray3=np.zeros((5,5))
print(myarray3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
myarray4=np.full((3,6),10)
print(myarray4)
myarray5=np.eye(5)
print(myarray5)
myarray6=np.ones((5,5))
print(myarray6)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
myarray7=np.random.random((5,5))
print(myarray7)

[[0.08845347 0.33936175 0.10553985 0.75352809 0.73757497]
 [0.73845049 0.6196295  0.28527747 0.82244166 0.72671996]
 [0.6863105  0.37389522 0.320163   0.66227454 0.64487985]
 [0.42993583 0.9444679  0.01498862 0.60199323 0.51429333]
 [0.35095761 0.67505299 0.16338879 0.5131845  0.45518392]]


In [20]:
myarray8=np.random.randint(100,size=(5,5))
print(myarray8)

[[24 44  3 46 73]
 [37 48 22 11 67]
 [46 15 62 42 60]
 [16 83 88 26 23]
 [44 42 53 86 41]]


In [19]:
newMatrix=myarray8[:2,:2]
print(newMatrix)

[[53 11]
 [23 51]]


In [23]:
newMatrix=myarray8[:2,:2]
print(newMatrix)

[[24 44]
 [37 48]]


In [25]:
myarray8[2,2]=10000
print(myarray8)

[[   24    44     3    46    73]
 [   37    48    22    11    67]
 [   46    15 10000    42    60]
 [   16    83    88    26    23]
 [   44    42    53    86    41]]


In [26]:
print(myarray8[2,:])

[   46    15 10000    42    60]


In [29]:
print(myarray8[:,2].shape)


(5,)


In [35]:
newMatrix=myarray8[1:4:,1:4]
print(newMatrix)

[[   48    22    11]
 [   15 10000    42]
 [   83    88    26]]
