<a href="https://colab.research.google.com/github/Ricardoarteaga24/InteligenciaArtificial_8vo/blob/main/Numpy_2_5noviembre/2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
matrixA=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(matrixA.shape)


(3, 4)


In [2]:
matrixA

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [3]:
print(matrixA[1:,1:3])

[[22 23]
 [32 33]]


In [10]:
# prompt: crear una matrix de 4x3 randon de numeros enteros


matrixB = np.random.randint(0, 10, size=(4, 3))

matrixB

array([[6, 7, 3],
       [2, 4, 1],
       [6, 6, 5],
       [2, 5, 7]])

In [17]:
print(matrixB)
col_indices=np.array([0,1,2])
row_indices=np.array([1,2])

for row,col in zip(row_indices,col_indices):
 # print(row,"-",col)
  print(matrixB[row,col])


[[6 7 3]
 [2 4 1]
 [6 6 5]
 [2 5 7]]
2
6


In [18]:
mask=matrixB>5
print(mask)

[[ True  True False]
 [False False False]
 [ True  True False]
 [False False  True]]


In [19]:
print(matrixB[mask])

[6 7 6 6 7]


In [20]:
print(matrixB[matrixB>5])

[6 7 6 6 7]


In [21]:
matrixB_modified = np.where(matrixB % 2 == 0, matrixB + 100, matrixB)

print("\nMatriz B modificada:")
matrixB_modified


Matriz B modificada:


array([[106,   7,   3],
       [102, 104,   1],
       [106, 106,   5],
       [102,   5,   7]])

In [22]:
matrixB[matrixB % 2 == 0] += 100
matrixB

array([[106,   7,   3],
       [102, 104,   1],
       [106, 106,   5],
       [102,   5,   7]])

In [24]:
mask = (matrixB >= 3) & (matrixB <= 9)

# Add 100 to the selected elements
matrixB_modified = np.where(mask, matrixB + 100, matrixB)


print("\nMatriz B modificada:")
matrixB_modified


Matriz B modificada:


array([[106, 107, 103],
       [102, 104,   1],
       [106, 106, 105],
       [102, 105, 107]])

In [27]:
matrixB[(matrixB>3) & (matrixB<9)] += 100
matrixB

array([[106, 107,   3],
       [102, 104,   1],
       [106, 106, 105],
       [102, 105, 107]])

In [ ]:
Filter=((matrixB>3)&(matrixB<9))
matrixB[Filter]+=100
print(matrixB)

In [31]:
matrixA1=np.random.randint(0,10 , size=(2,2))
matrixA2=np.random.randint(0,10 , size=(2,2))


In [29]:
print(matrixA1+matrixA2)
print(matrixA1-matrixA2)
print(matrixA1*matrixA2)
print(matrixA1/matrixA2)
print(np.sqrt(matrixA1))


[[ 8  8]
 [14  3]]
[[ 4  4]
 [ 0 -1]]
[[12 12]
 [49  2]]
[[3.  3. ]
 [1.  0.5]]
[[2.44948974 2.44948974]
 [2.64575131 1.        ]]


In [32]:
print(matrixA1)

[[5 9]
 [7 1]]


In [33]:
print(np.sqrt(matrixA1))

[[2.23606798 3.        ]
 [2.64575131 1.        ]]


In [46]:
matrixA3=np.random.randint(0,10 , size=(2,5))
print(matrixA3)

[[7 8 9 3 0]
 [2 0 8 1 2]]


In [35]:
print(np.mean(matrixA3))

4.3


In [37]:
print(matrixA3.mean(axis=1))

[6.8 3.8]


In [38]:
print(matrixA3.mean(axis=0))

[5.5 7.  4.  3.5 6.5]


In [39]:
print(np.std(matrixA3))

2.6095976701399777


In [41]:
print(np.median(matrixA3))

6.0


In [43]:
print(matrixA3.sum())

53


In [44]:
print(matrixA3.max())

8


In [48]:
start=np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [47]:
add_rows=np.array([1,2,3])
print(add_rows.shape)

(3,)


In [49]:
y=start+add_rows
print(y)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [50]:
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [58]:
col_rows=np.array([1,2,3,4])

In [ ]:
print(start)
tmp=col_rows.T
y2=start+tmp
print(y2)

In [59]:
tmp1=np.array([[1,1],[2,2]])
tmp2=np.array([[3,3],[4,4]])
print(tmp1)
print(tmp2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [ ]:
print(np.dot(tmp1,tmp2))

In [60]:

matrix1 = np.random.randint(2, 51, size=(2, 2))
matrix2 = np.random.randint(2, 51, size=(2, 2))

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
matrix2

Matrix 1:
[[25 32]
 [35 16]]

Matrix 2:


array([[ 7,  9],
       [ 9, 23]])

In [62]:
np.vstack((matrix1,matrix2))

array([[25, 32],
       [35, 16],
       [ 7,  9],
       [ 9, 23]])

In [63]:
np.hstack((matrix1,matrix2))

array([[25, 32,  7,  9],
       [35, 16,  9, 23]])